### ISSUE TITLE
large screen push menu

### ISSUE THREAD

**Issue by ccaterinaghost** [ccaterinaghost/ucsusa#38]
![screen shot 2015-02-18 at 1 45 21 pm](https://cloud.githubusercontent.com/assets/6333787/6254164/93a9769e-b774-11e4-9ba1-e198163e863d.png)

should only take up 30% of screen. currently takes up close to 50%. too wide.

**Comment by Bekka666** [comment]
This seems to be fine now.

**Comment by Bekka666** [comment]
This seems to only occur on medium & small. (I can see having it wider on small screens to actually be able to use the buttons.) On medium screens, the donate button starts touching the logo in the nav.

**Comment by birchy009** [comment]
I did 100% small, 50% med and 30% large. I tried the site on my phone and 30% didnt cut it, i couldnt touch a link easy enough
