### ISSUE TITLE
donate page buckets

### ISSUE THREAD

**Issue by ccaterinaghost** [ccaterinaghost/ucsusa#39]
![screen shot 2015-02-18 at 1 47 39 pm](https://cloud.githubusercontent.com/assets/6333787/6254184/bd7b731e-b774-11e4-8bd6-0d626f6fb689.png)

some text is cut off in buckets. make text size smaller?

**Comment by birchy009** [comment]
cant seem to replicate, mine looks like this:
![screen shot 2015-02-19 at 10 45 38](https://cloud.githubusercontent.com/assets/6340876/6269939/85daaf96-b824-11e4-808b-f9afc83db1e9.png)

**Comment by Bekka666** [comment]
The header becomes too big, overlapping the buckets. I think this is an issue with the media queries.

**Comment by Bekka666** [comment]
It looks normal when full screen. When you play with the window sizing, the nav overlaps the buckets.

**Comment by birchy009** [comment]
it was the media queries, ive fixed it now
