### ISSUE TITLE
become a member button on take action page. match to style on about page.

### ISSUE THREAD

**Issue by ccaterinaghost** [ccaterinaghost/ucsusa#41]
![screen shot 2015-02-18 at 1 50 22 pm](https://cloud.githubusercontent.com/assets/6333787/6254242/20016f2a-b775-11e4-8fc9-03242e3a6058.png)

add white border around box or some padding around text to make these buttons - box too tight around text - problem only appears on take action page

**Comment by Bekka666** [comment]
Inspect element says padding: 0; is overriding the padding on the buttons.

**Comment by Bekka666** [comment]
Inspect element says .news h4 padding: 0; is overriding padding: 0.5em; on .involve-link.

**Comment by birchy009** [comment]
im seeing 
![screen shot 2015-02-19 at 10 47 20](https://cloud.githubusercontent.com/assets/6340876/6269970/b5d7fe6a-b824-11e4-8f7a-7df12f3ae799.png)

**Comment by Bekka666** [comment]
This is weird.. Maybe it's because you have a retina laptop? Maybe it's something in the resolution of our laptops that's making the site look a little more compact. (Just a thought.)

**Comment by Bekka666** [comment]
NVM just refreshed. It looks fine now.

**Comment by birchy009** [comment]
its possible you guys were looking at a cached version of the site, its best to open it in an incognito window to get all the newest code
